# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='stu_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
