# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_id', '0003_auto_20160603_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
