# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_id', '0004_info_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='bc_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='bc_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='cf_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='cf_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='bc_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='cf_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='soj_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
